### ISSUE TITLE
Plugin Crash

### ISSUE THREAD

**Issue by DracoClaw** [asportnoy/member-count#3]
When switching channels the plugin is causing the client to crash. 

canary 279864 (f736de7) Host 1.0.206 x86 (45799) Windows 10 64-bit (10.0.19045)

```
24321.e99606dee64622c47cfb.js:1 [Replugged:Plugin:MemberCount] Failed to fetch guild popout for 1000926524452647132 TypeError: Cannot read properties of undefined (reading 'get')
    at v (renderer.js?t=1711721323557:1:1073)
    at y (renderer.js?t=1711721323557:1:2470)
    at 24321.e99606dee64622c47cfb.js:1:7032846
    at Set.forEach (<anonymous>)
    at r.invokeAll (24321.e99606dee64622c47cfb.js:1:7032835)
    at 24321.e99606dee64622c47cfb.js:1:7040823
    at Set.forEach (<anonymous>)
    at e.emitNonReactOnce (24321.e99606dee64622c47cfb.js:1:7040783)
    at 24321.e99606dee64622c47cfb.js:1:7040155
    at sA (58661.f2f726c2fd11e3798966.js:12:935422)
    at r (24321.e99606dee64622c47cfb.js:1:7529120)
    at e.emit (24321.e99606dee64622c47cfb.js:1:7039930)
    at T.flushWaitQueue (24321.e99606dee64622c47cfb.js:1:7034632)
    at 24321.e99606dee64622c47cfb.js:1:7034155
    at new Promise (<anonymous>)
    at T.dispatch (24321.e99606dee64622c47cfb.js:1:7033904)
    at a (24321.e99606dee64622c47cfb.js:1:273812)
    at 24321.e99606dee64622c47cfb.js:1:2346766
    at 58661.f2f726c2fd11e3798966.js:12:67134
    at nQ (58661.f2f726c2fd11e3798966.js:12:56936)
    at 58661.f2f726c2fd11e3798966.js:12:66939
    at Function.a_ (58661.f2f726c2fd11e3798966.js:12:79534)
    at 24321.e99606dee64622c47cfb.js:1:2346725
    at oF (58661.f2f726c2fd11e3798966.js:12:922816)
    at oU (58661.f2f726c2fd11e3798966.js:12:923012)
    at sj (58661.f2f726c2fd11e3798966.js:12:951171)
    at 58661.f2f726c2fd11e3798966.js:12:950658
    at sY (58661.f2f726c2fd11e3798966.js:12:950723)
    at sM (58661.f2f726c2fd11e3798966.js:12:935351)
    at r6 (58661.f2f726c2fd11e3798966.js:12:883839)
    at 58661.f2f726c2fd11e3798966.js:12:950718
    at sY (58661.f2f726c2fd11e3798966.js:12:950723)
    at sT (58661.f2f726c2fd11e3798966.js:12:934092)
    at x (58661.f2f726c2fd11e3798966.js:12:1125228)
    at A (58661.f2f726c2fd11e3798966.js:12:1125758)
    at D.<computed> (58661.f2f726c2fd11e3798966.js:1:502282)
    at M (58661.f2f726c2fd11e3798966.js:1:502047)
    at MessagePort.k (58661.f2f726c2fd11e3798966.js:1:502106)```

**Comment by Czekoloczek** [comment]
same for me, still not fixed
also, these errors are spamming the console even if you don't switch channels
